// loam — the docs index, generated rather than kept by hand.
//
// Copyright (c) 2026 Oddur Sigurdsson. MIT licensed; see LICENSE.
//
// cairn renders a whole ROADMAP.md from a header file and the items. An index
// is different: it is a page people also write in — poptop's opens with what
// its three kinds are for and ends with links out of the docs folder. So loam
// owns only what lies between two markers, and the rest of the file is the
// project's. That is the header and footer cairn keeps in separate files, kept
// in the one file a reader actually opens.

use crate::tree::{Page, Tree};
use crate::write::{Lines, dir_of, encode_destination, relative};
use anyhow::{Result, bail};

pub const BEGIN: &str = "<!-- loam:index:begin -->";
pub const END: &str = "<!-- loam:index:end -->";
const NOTE: &str =
    "<!-- Generated by `loam render` from the pages below; edit those, not this. -->";

fn cell(s: &str) -> String {
    s.replace('|', "\\|")
}

fn row(index_dir: &str, page: &Page, extra: Option<String>) -> String {
    let title = page
        .title
        .clone()
        .unwrap_or_else(|| page.path.rsplit('/').next().unwrap_or("").to_string());
    // A link in the title would be a link inside the row's link, which
    // Markdown reads as the inner link alone: the row would not reach the page.
    let mut link = format!(
        "[{}]({})",
        cell(&crate::scan::unlinked(&title)),
        encode_destination(&relative(index_dir, &page.path))
    );
    if page.status == "draft" {
        link.push_str(" *(draft)*");
    }
    let note = match extra {
        Some(e) => e,
        None => lead_of(page)
            .map(|s| rebase(s, page, index_dir))
            .unwrap_or_default(),
    };
    format!("| {link} | {} |", cell(&note))
}

/// The first sentence of a paragraph (0066). A summary somebody wrote in
/// frontmatter is shown whole — its length was chosen. One inferred from the
/// first paragraph was not, and a paragraph can run to eighty words, which
/// makes a row that is mostly one cell. A sentence ends at `.`, `?` or `!`
/// before a space, unless it closes a common abbreviation or sits inside a
/// code span, link or parentheses.
/// Whole sentences from the start of `text`, as many as fit in `limit` bytes,
/// and always at least one: a paragraph's opening, without a cut mid-thought.
pub fn lead(text: &str, limit: usize) -> &str {
    let mut end = first_sentence(text).len();
    while end < text.len() {
        let rest = text[end..].trim_start();
        let next = end + (text.len() - end - rest.len()) + first_sentence(rest).len();
        if next > limit {
            break;
        }
        end = next;
    }
    &text[..end]
}

pub fn first_sentence(text: &str) -> &str {
    const ABBREVIATIONS: &[&str] = &[
        "e.g.", "i.e.", "etc.", "vs.", "cf.", "approx.", "no.", "dr.", "mr.", "ms.", "st.",
    ];
    let b = text.as_bytes();
    let (mut code, mut depth) = (false, 0i32);
    for (i, &c) in b.iter().enumerate() {
        match c {
            b'`' => code = !code,
            b'[' | b'(' if !code => depth += 1,
            b']' | b')' if !code => depth -= 1,
            b'.' | b'?' | b'!' if !code && depth <= 0 && b.get(i + 1) == Some(&b' ') => {
                let word = text[..=i].rsplit(' ').next().unwrap_or("");
                if !ABBREVIATIONS.iter().any(|a| word.eq_ignore_ascii_case(a)) {
                    return &text[..=i];
                }
            }
            _ => {}
        }
    }
    text
}

/// A summary's relative links, rewritten to work from the index rather than
/// from the page they were written in. The summary is one line of Markdown, so
/// the same scan that finds a page's links finds them here.
fn rebase(summary: &str, page: &Page, index_dir: &str) -> String {
    let blocks = crate::scan::blocks(summary, 1);
    let mut links = crate::scan::links(&blocks, &|_| None);
    links.sort_by_key(|l| std::cmp::Reverse(l.start));
    let mut out = summary.to_string();
    for link in links {
        let dest = &link.destination;
        if dest.starts_with('/') {
            continue;
        }
        // `#section` meant a place on the page itself, which from the index
        // is that page's path and the same fragment.
        let target = match crate::tree::resolve(&page.path, dest) {
            (Some(target), _, "path" | "self") => target,
            _ => continue,
        };
        let cut = dest.find(['?', '#']).unwrap_or(dest.len());
        let mut path = relative(index_dir, &target);
        if dest[..cut].ends_with('/') {
            path.push('/');
        }
        let path = if link.angle {
            path
        } else {
            encode_destination(&path)
        };
        out.replace_range(link.start..link.end, &format!("{path}{}", &dest[cut..]));
    }
    out
}

fn sorted(mut pages: Vec<&Page>) -> Vec<&Page> {
    pages.sort_by(|a, b| {
        (
            a.order.unwrap_or(i64::MAX),
            a.title.as_deref().map(str::to_lowercase),
            &a.path,
        )
            .cmp(&(
                b.order.unwrap_or(i64::MAX),
                b.title.as_deref().map(str::to_lowercase),
                &b.path,
            ))
    });
    pages
}

/// One section of the index: a kind's pages, the pages no declared kind
/// holds, or the superseded ones. `render` writes these as Markdown and
/// `index --json` as the manifest's `sections`, so the two cannot disagree.
pub struct Section<'a> {
    /// `kind`, `other` or `superseded`.
    pub role: &'static str,
    /// The kind's name, for a kind's section.
    pub kind: Option<&'a str>,
    pub heading: String,
    pub description: Option<&'a str>,
    /// In the index's order: `order`, then title.
    pub pages: Vec<&'a Page>,
}

/// The index's sections, in order, each with its pages; empty ones left out.
pub fn sections(tree: &Tree) -> Vec<Section<'_>> {
    let index = &tree.config.index;
    let listed = |p: &&Page| p.path != *index;
    let mut out = Vec::new();

    for kind in tree.config.kinds.iter().filter(|k| k.index) {
        let pages: Vec<&Page> = tree
            .pages
            .values()
            .filter(listed)
            .filter(|p| p.status != "superseded" && p.kind.as_deref() == Some(kind.name.as_str()))
            .collect();
        if !pages.is_empty() {
            out.push(Section {
                role: "kind",
                kind: Some(&kind.name),
                heading: kind.heading(),
                description: kind
                    .description
                    .as_deref()
                    .map(str::trim)
                    .filter(|d| !d.is_empty()),
                pages: sorted(pages),
            });
        }
    }

    // Pages whose kind is not declared, or that no kind claims: listed rather
    // than hidden, because `check` is already saying something about them.
    let declared = |p: &&Page| {
        p.kind
            .as_deref()
            .is_some_and(|k| tree.config.kind(k).is_some())
    };
    let other: Vec<&Page> = tree
        .pages
        .values()
        .filter(listed)
        .filter(|p| p.status != "superseded" && !declared(p))
        .collect();
    if !other.is_empty() {
        out.push(Section {
            role: "other",
            kind: None,
            heading: "Other".into(),
            description: None,
            pages: sorted(other),
        });
    }

    let superseded: Vec<&Page> = tree
        .pages
        .values()
        .filter(listed)
        .filter(|p| p.status == "superseded")
        .filter(|p| {
            p.kind
                .as_deref()
                .and_then(|k| tree.config.kind(k))
                .is_none_or(|k| k.index)
        })
        .collect();
    if !superseded.is_empty() {
        out.push(Section {
            role: "superseded",
            kind: None,
            heading: "Superseded".into(),
            description: Some(
                "Kept because a link may still land here, and because what they argued is still evidence.",
            ),
            pages: sorted(superseded),
        });
    }
    out
}

/// The generated block, markers included, as lines without endings.
pub fn generate(tree: &Tree) -> Vec<String> {
    let index_dir = dir_of(&tree.config.index);
    let mut out = vec![BEGIN.to_string(), NOTE.to_string()];
    for section in sections(tree) {
        out.push(String::new());
        out.push(format!("## {}", section.heading));
        if let Some(d) = section.description {
            out.push(String::new());
            out.extend(d.lines().map(str::to_string));
        }
        out.push(String::new());
        out.push("| | |".into());
        out.push("|---|---|".into());
        for p in section.pages {
            let note = (section.role == "superseded").then(|| {
                let by: Vec<String> = p
                    .superseded_by
                    .iter()
                    .filter_map(|v| crate::tree::resolve(&p.path, v).0)
                    .map(|t| {
                        let title = tree
                            .pages
                            .get(&t)
                            .and_then(|q| q.title.clone())
                            .unwrap_or_else(|| t.clone());
                        format!(
                            "[{}]({})",
                            cell(&crate::scan::unlinked(&title)),
                            encode_destination(&relative(index_dir, &t))
                        )
                    })
                    .collect();
                if by.is_empty() {
                    String::new()
                } else {
                    format!("replaced by {}", by.join(", "))
                }
            });
            out.push(row(index_dir, p, note));
        }
    }
    out.push(String::new());
    out.push(END.to_string());
    out
}

/// A page's summary as the index shows it: a paragraph loam took cut to its
/// opening sentences (0066), one written in frontmatter whole.
pub fn lead_of(page: &Page) -> Option<&str> {
    page.summary.as_deref().map(|s| {
        if page.summary_from == Some("paragraph") {
            lead(s, 160)
        } else {
            s
        }
    })
}

pub enum Target {
    /// The file does not exist yet; this is what it would hold.
    New(String),
    /// The file exists; this is what it would hold after rendering.
    Existing { current: String, rendered: String },
}

/// What rendering would make of the index file.
pub fn render(tree: &Tree) -> Result<Target> {
    let generated = generate(tree);
    let path = tree.config.abs(&tree.config.index);
    if !path.exists() {
        let mut text = String::from("# Documentation\n\n");
        for l in &generated {
            text.push_str(l);
            text.push('\n');
        }
        return Ok(Target::New(text));
    }
    let current = std::fs::read_to_string(&path)?;
    let mut lines = Lines::parse(&current);
    let Some((begin, end)) = crate::write::markers(&lines, BEGIN, END) else {
        bail!(
            "{} has no place for the index\n\
             add these two lines where it belongs, then run `loam render`:\n\n    {BEGIN}\n    {END}\n\n\
             each alone on its line and outside code; everything outside them stays as you wrote it",
            tree.config.index
        );
    };
    crate::write::replace_lines(&mut lines, begin, end, &generated);
    Ok(Target::Existing {
        rendered: lines.render(),
        current,
    })
}

#[cfg(test)]
mod tests {
    use super::{first_sentence, lead};

    #[test]
    fn first_sentences() {
        assert_eq!(first_sentence("One. Two."), "One.");
        assert_eq!(first_sentence("Uses e.g. this. Then."), "Uses e.g. this.");
        assert_eq!(
            first_sentence("Run `make x. y` now. Then."),
            "Run `make x. y` now."
        );
        assert_eq!(
            first_sentence("See [a. b](x.md) here. More."),
            "See [a. b](x.md) here."
        );
        assert_eq!(first_sentence("No end"), "No end");
        assert_eq!(first_sentence("Is it? Yes."), "Is it?");
        assert_eq!(
            first_sentence("Version 1.2 is out. Ok."),
            "Version 1.2 is out."
        );
        assert_eq!(
            lead("Thanks! This says what it is. And more besides.", 30),
            "Thanks! This says what it is."
        );
        assert_eq!(
            lead("A very long first sentence indeed. Short.", 10),
            "A very long first sentence indeed."
        );
        assert_eq!(lead("One. Two. Three.", 100), "One. Two. Three.");
    }
}
