// loam — the docs index, generated rather than kept by hand.
//
// Copyright (c) 2026 Oddur Sigurdsson. MIT licensed; see LICENSE.
//
// cairn renders a whole ROADMAP.md from a header file and the items. An index
// is different: it is a page people also write in — poptop's opens with what
// its three kinds are for and ends with links out of the docs folder. So loam
// owns only what lies between two markers, and the rest of the file is the
// project's. That is the header and footer cairn keeps in separate files, kept
// in the one file a reader actually opens.

use crate::tree::{Page, Tree};
use crate::write::{Lines, dir_of, encode_destination, relative};
use anyhow::{Result, bail};

pub const BEGIN: &str = "<!-- loam:index:begin -->";
pub const END: &str = "<!-- loam:index:end -->";
const NOTE: &str =
    "<!-- Generated by `loam render` from the pages below; edit those, not this. -->";

fn cell(s: &str) -> String {
    s.replace('|', "\\|")
}

fn row(index_dir: &str, page: &Page, extra: Option<String>) -> String {
    let title = page
        .title
        .clone()
        .unwrap_or_else(|| page.path.rsplit('/').next().unwrap_or("").to_string());
    let mut link = format!(
        "[{}]({})",
        cell(&title),
        encode_destination(&relative(index_dir, &page.path))
    );
    if page.status == "draft" {
        link.push_str(" *(draft)*");
    }
    let note = match extra {
        Some(e) => e,
        None => page
            .summary
            .as_deref()
            .map(|s| rebase(s, page, index_dir))
            .unwrap_or_default(),
    };
    format!("| {link} | {} |", cell(&note))
}

/// A summary's relative links, rewritten to work from the index rather than
/// from the page they were written in. The summary is one line of Markdown, so
/// the same scan that finds a page's links finds them here.
fn rebase(summary: &str, page: &Page, index_dir: &str) -> String {
    let blocks = crate::scan::blocks(summary, 1);
    let mut links = crate::scan::links(&blocks, &|_| None);
    links.sort_by_key(|l| std::cmp::Reverse(l.start));
    let mut out = summary.to_string();
    for link in links {
        let dest = &link.destination;
        if dest.starts_with('/') || dest.starts_with('#') {
            continue;
        }
        let (Some(target), _, "path") = crate::tree::resolve(&page.path, dest) else {
            continue;
        };
        let cut = dest.find(['?', '#']).unwrap_or(dest.len());
        let mut path = relative(index_dir, &target);
        if dest[..cut].ends_with('/') {
            path.push('/');
        }
        let path = if link.angle {
            path
        } else {
            encode_destination(&path)
        };
        out.replace_range(link.start..link.end, &format!("{path}{}", &dest[cut..]));
    }
    out
}

fn sorted(mut pages: Vec<&Page>) -> Vec<&Page> {
    pages.sort_by(|a, b| {
        (
            a.order.unwrap_or(i64::MAX),
            a.title.as_deref().map(str::to_lowercase),
            &a.path,
        )
            .cmp(&(
                b.order.unwrap_or(i64::MAX),
                b.title.as_deref().map(str::to_lowercase),
                &b.path,
            ))
    });
    pages
}

/// The generated block, markers included, as lines without endings.
pub fn generate(tree: &Tree) -> Vec<String> {
    let index = &tree.config.index;
    let index_dir = dir_of(index);
    let listed = |p: &&Page| p.path != *index;
    let mut out = vec![BEGIN.to_string(), NOTE.to_string()];

    let table = |out: &mut Vec<String>, rows: Vec<String>| {
        out.push(String::new());
        out.push("| | |".into());
        out.push("|---|---|".into());
        out.extend(rows);
    };

    for kind in tree.config.kinds.iter().filter(|k| k.index) {
        let pages: Vec<&Page> = tree
            .pages
            .values()
            .filter(listed)
            .filter(|p| p.status != "superseded" && p.kind.as_deref() == Some(kind.name.as_str()))
            .collect();
        if pages.is_empty() {
            continue;
        }
        out.push(String::new());
        out.push(format!("## {}", kind.heading()));
        if let Some(d) = kind
            .description
            .as_deref()
            .map(str::trim)
            .filter(|d| !d.is_empty())
        {
            out.push(String::new());
            out.extend(d.lines().map(str::to_string));
        }
        let rows = sorted(pages)
            .into_iter()
            .map(|p| row(index_dir, p, None))
            .collect();
        table(&mut out, rows);
    }

    // Pages whose kind is not declared, or that no kind claims: listed rather
    // than hidden, because `check` is already saying something about them.
    let declared = |p: &&Page| {
        p.kind
            .as_deref()
            .is_some_and(|k| tree.config.kind(k).is_some())
    };
    let other: Vec<&Page> = tree
        .pages
        .values()
        .filter(listed)
        .filter(|p| p.status != "superseded" && !declared(p))
        .collect();
    if !other.is_empty() {
        out.push(String::new());
        out.push("## Other".into());
        let rows = sorted(other)
            .into_iter()
            .map(|p| row(index_dir, p, None))
            .collect();
        table(&mut out, rows);
    }

    let superseded: Vec<&Page> = tree
        .pages
        .values()
        .filter(listed)
        .filter(|p| p.status == "superseded")
        .filter(|p| {
            p.kind
                .as_deref()
                .and_then(|k| tree.config.kind(k))
                .is_none_or(|k| k.index)
        })
        .collect();
    if !superseded.is_empty() {
        out.push(String::new());
        out.push("## Superseded".into());
        out.push(String::new());
        out.push("Kept because a link may still land here, and because what they argued is still evidence.".into());
        let rows = sorted(superseded)
            .into_iter()
            .map(|p| {
                let by: Vec<String> = p
                    .superseded_by
                    .iter()
                    .filter_map(|v| crate::tree::resolve(&p.path, v).0)
                    .map(|t| {
                        let title = tree
                            .pages
                            .get(&t)
                            .and_then(|q| q.title.clone())
                            .unwrap_or_else(|| t.clone());
                        format!(
                            "[{}]({})",
                            cell(&title),
                            encode_destination(&relative(index_dir, &t))
                        )
                    })
                    .collect();
                let note = if by.is_empty() {
                    String::new()
                } else {
                    format!("replaced by {}", by.join(", "))
                };
                row(index_dir, p, Some(note))
            })
            .collect();
        table(&mut out, rows);
    }

    out.push(String::new());
    out.push(END.to_string());
    out
}

pub enum Target {
    /// The file does not exist yet; this is what it would hold.
    New(String),
    /// The file exists; this is what it would hold after rendering.
    Existing { current: String, rendered: String },
}

/// What rendering would make of the index file.
pub fn render(tree: &Tree) -> Result<Target> {
    let generated = generate(tree);
    let path = tree.config.abs(&tree.config.index);
    if !path.exists() {
        let mut text = String::from("# Documentation\n\n");
        for l in &generated {
            text.push_str(l);
            text.push('\n');
        }
        return Ok(Target::New(text));
    }
    let current = std::fs::read_to_string(&path)?;
    let mut lines = Lines::parse(&current);
    let find = |marker: &str| lines.lines.iter().position(|(l, _)| l.trim() == marker);
    let (Some(begin), Some(end)) = (find(BEGIN), find(END)) else {
        bail!(
            "{} has no place for the index\n\
             add these two lines where it belongs, then run `loam render`:\n\n    {BEGIN}\n    {END}\n\n\
             everything outside them stays as you wrote it",
            tree.config.index
        );
    };
    if end < begin {
        bail!("{}: `{END}` comes before `{BEGIN}`", tree.config.index);
    }
    let eol = lines.eol();
    let last = lines.lines[end].1;
    lines.lines.drain(begin..=end);
    for (i, l) in generated.iter().enumerate() {
        lines.lines.insert(begin + i, (l.clone(), eol));
    }
    lines.lines[begin + generated.len() - 1].1 = last;
    Ok(Target::Existing {
        rendered: lines.render(),
        current,
    })
}
